### ISSUE TITLE
`anvil.ps1  build` does not build the DotNet container

### ISSUE THREAD

**Issue by AndreTheHunter** [axrs/anvil#5]
`./anvil.ps1 build` produces and error that includes
```
#6 3.725 E: Unable to locate package dart
#6 3.725 E: Unable to locate package powershell
```

```
2022-06-21 16:24:19.471316 | INFO    | af:build       : Building axrs/anvil:base
Unhandled exception:
ChassisShellException executing: docker build \
  --progress plain \
   --pull \
  --tag axrs/anvil:base \
  --file Base.Dockerfile \
   \
  .docker_context

docker build --progress plain --pull --tag axrs/anvil:base --file Base.Dockerfile .docker_context, exitCode 1, workingDirectory: /Users/andre/Projects/anvil
-----
#2 [internal] load .dockerignore
#2 sha256:3c32024e8ed9ce761ef8419f571e42955c837b1030e35653fbe4f8116fe792f8
#2 transferring context:
#2 transferring context: 2B 0.0s done
#2 DONE 0.1s

#1 [internal] load build definition from Base.Dockerfile
#1 sha256:17d35d6516ff06c9d6ff61ea42affeb5a6e8c232fffc8aaf68127110019ecd29
#1 transferring dockerfile: 42B 0.0s done
#1 DONE 0.1s

#3 [internal] load metadata for docker.io/library/debian:bullseye-slim
#3 sha256:0a5e3537f6f00069b5f0ddc33b847bdbbcb70a30443a039ccea22aa84eb155d5
#3 DONE 3.9s

#4 [1/4] FROM docker.io/library/debian:bullseye-slim@sha256:06a93cbdd49a265795ef7b24fe374fee670148a7973190fb798e43b3cf7c5d0f
#4 sha256:a1489de6e8b2fc320c45c6bf53e171c40e476f94132c0ce2ce99ff39443b796d
#4 DONE 0.0s

#5 [2/4] RUN export DEBIAN_FRONTEND=noninteractive  && apt-get --quiet --yes update  && apt-get --quiet --yes upgrade  && apt-get --quiet --yes --no-install-recommends install     apt-transport-https     ca-certificates     curl     git     gnupg     openssh-client     unzip  && echo '----- Additional Package Repositories'  && echo '      -- Node.js'  && curl -sL 'https://deb.nodesource.com/setup_12.x' | bash  && echo '      -- Dart Package Repository'  && sh -c 'curl -sLk https://dl-ssl.google.com/linux/linux_signing_key.pub | apt-key add -'  && sh -c 'curl -sLk https://storage.googleapis.com/download.dartlang.org/linux/debian/dart_stable.list > /etc/apt/sources.list.d/dart_stable.list'  && echo '      -- Microsoft'  && curl -sL 'https://packages.microsoft.com/config/debian/11/packages-microsoft-prod.deb' -o 'packages-microsoft-prod.deb'  && dpkg -i 'packages-microsoft-prod.deb'
#5 sha256:95b8846d855e4afb0c6cfe813865cbe4d1d536f55e1cbcef78188968f95dea72
#5 CACHED

#6 [3/4] RUN echo '---- Installs'  && apt-get --quiet update  && DEBIAN_FRONTEND=noninteractive apt-get install -y --no-install-recommends     dart="$DART_VERSION"     nodejs     powershell  && curl -fsSL https://aka.ms/install-artifacts-credprovider.sh  && echo '----- Build Cleanup'  && apt-get --quiet --purge --yes remove      apt-transport-https     gnupg     unzip
#6 sha256:1e44dc9db9ccfb29a895885b6200aeacc8c1bb84916cdcb2b29dbbd565052da8
#6 0.978 ---- Installs
#6 1.332 Get:1 http://security.debian.org/debian-security bullseye-security InRelease [44.1 kB]
#6 1.344 Hit:2 https://deb.nodesource.com/node_12.x bullseye InRelease
#6 1.510 Ign:3 https://storage.googleapis.com/download.dartlang.org/linux/debian stable InRelease
#6 1.529 Hit:4 http://deb.debian.org/debian bullseye InRelease
#6 1.541 Get:5 http://security.debian.org/debian-security bullseye-security/main arm64 Packages [159 kB]
#6 1.603 Get:6 http://deb.debian.org/debian bullseye-updates InRelease [39.4 kB]
#6 1.739 Get:7 https://packages.microsoft.com/debian/11/prod bullseye InRelease [10.5 kB]
#6 1.746 Get:8 https://storage.googleapis.com/download.dartlang.org/linux/debian stable Release [944 B]
#6 1.946 Get:9 https://packages.microsoft.com/debian/11/prod bullseye/main arm64 Packages [12.7 kB]
#6 2.085 Get:10 https://packages.microsoft.com/debian/11/prod bullseye/main amd64 Packages [63.8 kB]
#6 2.121 Get:11 https://storage.googleapis.com/download.dartlang.org/linux/debian stable Release.gpg [819 B]
#6 2.258 Get:12 https://packages.microsoft.com/debian/11/prod bullseye/main armhf Packages [14.5 kB]
#6 2.847 Get:13 https://storage.googleapis.com/download.dartlang.org/linux/debian stable/main amd64 Packages [6004 B]
#6 2.890 Fetched 351 kB in 2s (196 kB/s)
#6 2.890 Reading package lists...
#6 3.253 Reading package lists...
#6 3.568 Building dependency tree...
#6 3.657 Reading state information...
#6 3.725 E: Unable to locate package dart
#6 3.725 E: Unable to locate package powershell
#6 ERROR: executor failed running [/bin/bash -o pipefail -c echo '---- Installs'  && apt-get --quiet update  && DEBIAN_FRONTEND=noninteractive apt-get install -y --no-install-recommends     dart="$DART_VERSION"     nodejs     powershell  && curl -fsSL https://aka.ms/install-artifacts-credprovider.sh  && echo '----- Build Cleanup'  && apt-get --quiet --purge --yes remove      apt-transport-https     gnupg     unzip]: exit code: 100
------
 > [3/4] RUN echo '---- Installs'  && apt-get --quiet update  && DEBIAN_FRONTEND=noninteractive apt-get install -y --no-install-recommends     dart="$DART_VERSION"     nodejs     powershell  && curl -fsSL https://aka.ms/install-artifacts-credprovider.sh  && echo '----- Build Cleanup'  && apt-get --quiet --purge --yes remove      apt-transport-https     gnupg     unzip:
------
executor failed running [/bin/bash -o pipefail -c echo '---- Installs'  && apt-get --quiet update  && DEBIAN_FRONTEND=noninteractive apt-get install -y --no-install-recommends     dart="$DART_VERSION"     nodejs     powershell  && curl -fsSL https://aka.ms/install-artifacts-credprovider.sh  && echo '----- Build Cleanup'  && apt-get --quiet --purge --yes remove      apt-transport-https     gnupg     unzip]: exit code: 100
-----
#0      ProcessRunShell.run (package:chassis_forge/src/shell.dart:250:9)
<asynchronous suspension>
#1      _buildDockerContainer (file:///Users/andre/Projects/anvil/tool/build.dart:31:3)
<asynchronous suspension>
#2      BuildCommand.run (file:///Users/andre/Projects/anvil/tool/build.dart:82:5)
<asynchronous suspension>
#3      ChassisCommand.execute (package:chassis_forge/chassis_forge.dart:63:5)
<asynchronous suspension>
```

**Comment by axrs** [comment]
Migrated away from Dart for building these images for simplicity. Dart may make an appearance again in the future.
